### ISSUE TITLE
Setup proper communication channels

### ISSUE THREAD

**Issue by antocuni** [pyhandle/hpy#4]
We will probably need to discuss tons of details and design decisions. Which tools should we use to keep track of them? I am not very familiar with "modern" tools, as in PyPy we are still using mostly IRC and mailing list 😅

- mailing list: should we make a new one or reuse capi-sig?

- should we use an IRC channel or something more modern like slack? Other ideas? 

- should we discuss design ideas on the ML or e.g. in github issues?

**Comment by windelbouwman** [comment]
A forum would be nice, then we have the discussion in some history. Currently I also use gitter.

Maybe we can use this forum? https://python-forum.io

**Comment by vstinner** [comment]
IMHO capi-sig is the best channel since it already exists.

**Comment by pmp-p** [comment]
i think a (modern!) forum is more suitable than a mailing list in the present case for some reasons :
 - Especially for non english native speakers who often need editing/confidence.
 - other python implementation projects :  those are often on discourse/gitter workflows.
 - H(andle)Py is for future no ?  Let's get 100% modern then since anyway there's a big cost of change involved.

gitter==irc.gitter.im for me the irc bridge is very capable so i'd vote gitter without hésitation
Since when you get disconnected a bit too long recent history is available via browser via a capable interface at no maintenance cost.

**Comment by antocuni** [comment]
We have open the IRC #hpy on freenode, btw

**Comment by antocuni** [comment]
And now we also have a mailing list: [hpy-dev@python.org](https://mail.python.org/mailman3/lists/hpy-dev.python.org/)
Probably having an IRC channel and a ML instead of a forum is not the most modern thing in the world, but I suppose they do their job well. Closing this issue
